# Generated by Django 3.2.5 on 2021-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('cust_id', models.PositiveIntegerField(unique=True)),
                ('invoice_amount_euro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_date', models.DateField()),
                ('revenue_charged_euro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_of_goods_euro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('account_invoice_received', models.PositiveIntegerField()),
                ('revenue_account_number', models.PositiveIntegerField()),
                ('operational_costs_euro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
